### ISSUE TITLE
[Request] Hide "For you" and "You might like" tweets

### ISSUE THREAD

**Issue by ethan-xd** [BandarHL/BHTwitter#108]
![image](https://user-images.githubusercontent.com/24442053/212500010-a27dc6b3-64b8-4b83-9926-b00ace1367b5.jpeg)
![image](https://user-images.githubusercontent.com/24442053/212793733-aab6b8f9-e35b-4148-8087-11b074b8e0f3.png)

This is basically Topic Tweets 2.0 with the most uninteresting unfunny stuff I've ever seen and would love if you could add the ability to hide it all. Thank you!

**Comment by ethan-xd** [comment]
@denwi No. It only hides tweets that are served under a topic. This is a new type of suggested tweet.

**Comment by ethan-xd** [comment]
There's another type of tweet I just remembered seeing but I don't have a reference photo. I'm not sure if you're able to block it based on this info, but it was something like "Popular in your area". If I ever see it again I'll post it here.

**Comment by PencilNotPen** [comment]
I’d also like this if possible. More than half my feed is now these new “you might like” posts, which are just a new type of sponsored/recommended posts. The existing toggles do not suppress them. Thanks for all your good work on BHTwitter!
