### ISSUE TITLE
[Request] Hide views in feed

### ISSUE THREAD

**Issue by ethan-xd** [BandarHL/BHTwitter#109]
![image](https://user-images.githubusercontent.com/24442053/212500228-603f6bb6-c2a2-47b3-888d-bd5e83027cfc.jpeg)

I feel it's unnecessary clutter which I would love if you could add the ability to block.

I'm not opposed to keeping the view count in the expanded tweet view, but just hiding it in the feed.

Thank you!

**Comment by DetachHead** [comment]
This was added in a recent update 
![9EA0D172-D19A-433F-B84E-16D47A35D9CF](https://user-images.githubusercontent.com/57028336/212500709-6715d13e-8148-465f-9473-1bb5c0f46e2e.png)

![05BAFE80-CDE0-44A6-ADF1-16DD3804C58C](https://user-images.githubusercontent.com/57028336/212500666-e28ea9ac-d866-4e4f-b410-95a19978fbe2.jpeg)

**Comment by ethan-xd** [comment]
well i didnt look 
![image](https://user-images.githubusercontent.com/24442053/212500729-e835258c-ec82-4f1e-8278-5e94a721e3bc.png)
