### ISSUE TITLE
[Request] Unread tweet count and removal of new tweet button.

### ISSUE THREAD

**Issue by Skates1616** [BandarHL/BHTwitter#114]
Would it be possible to add an unread tweet count as depicted below in the top right corner?

![4989A333-F2A6-4BAA-A968-3038EC710EA7](https://user-images.githubusercontent.com/23196661/212594621-679415d0-1186-42f5-b354-ea05bd7ffbbd.jpeg)

Also, would it be possible to create an option to remove this banner?

![8D29BF06-728D-482F-9C90-B3CF797DF55C](https://user-images.githubusercontent.com/23196661/212594727-bc26f3b6-737e-475a-be2a-a0a5215f1f19.jpeg)

I am a Tweetbot convert and touching this banner accidentally has resulted in me having to scroll down to where I left off.

**Comment by BandarHL** [comment]
Sorry it’s not possible
