### ISSUE TITLE
Download button overlaps with share button

### ISSUE THREAD

**Issue by DetachHead** [BandarHL/BHTwitter#13]
![12E05B7C-C2BA-4B8D-9EDB-9F769A79899A](https://user-images.githubusercontent.com/57028336/146688409-3fd0b056-11a1-4e31-8ec5-d9b592da4ec2.jpeg)

**Comment by BandarHL** [comment]
because you have another Tweak that pushing my Tweak button :)

**Comment by BandarHL** [comment]
is that DLEasy?

**Comment by DetachHead** [comment]
nah it's a downvote button, i think it's a feature twitter is A/B testing

**Comment by BandarHL** [comment]
And also i fix this annoying issue with the next update.
