### ISSUE TITLE
[Bug] Installation failed on iPhone 11

### ISSUE THREAD

**Issue by SHEN-Muchuan** [BandarHL/BHTwitter#133]
Device iPhone12,1 not in SupportedDevices list for com.atebits.Tweetie2.GDKH3RAC8C : (
    "iPhone10,2",
    "iPhone10,3",
    "iPhone10,5",
    "iPhone10,6",
    "iPhone11,2",
    "iPhone11,4",
    "iPhone11,6",
    "iPhone12,3",
    "iPhone12,5",
    "iPhone13,1",
    "iPhone13,2",
    "iPhone13,3",
    "iPhone13,4",
    "iPhone14,2",
    "iPhone14,3",
    "iPhone14,4",
    "iPhone14,5",
    "iPhone14,7",
    "iPhone14,8",
    "iPhone15,2",
    "iPhone15,3",
    "iPhone8,2",
    "iPhone9,2",
    "iPhone9,4"
)

**Comment by BandarHL** [comment]
Should be fixed with 3.9
