### ISSUE TITLE
[Bug] “Always start on Following” jumps to top of feed when exiting app (3.9.1)

### ISSUE THREAD

**Issue by rickymangerie** [BandarHL/BHTwitter#145]
Enabling the new “Always start on Following page” feature [makes the Twitter timeline jump to the top every time you leave the app](https://www.veed.io/embed/430886ad-69ce-4020-b462-c3bdc01346ff). This behavior seems to mimic if you were to press the top of the screen, which jumps to the top of the feed. Can confirm this is the cause of the issue, as [disabling this new feature makes the problem stop](https://www.veed.io/embed/aa302c51-c362-49e3-aed2-2a598971b4d4). (Sorry for the expletives on my Twitter timeline in the screen-recorded videos)

BHTwitter 3.9.1
iPhone 12 Pro
iOS 16.3
AltStore sideloaded

**Comment by ta6vie** [comment]
Yes this is also happening to me.
