### ISSUE TITLE
Add Chinese font 

### ISSUE THREAD

**Issue by Yumega** [BandarHL/BHTwitter#15]
please add some Chinese font，like

Microsoft YaHei
Microsoft YaHei Bold

thanks

**Comment by BandarHL** [comment]
BHTwitter doesn’t have fonts, its all system font if you want custom fonts download iFont app from app store and install your custom font.
After that go to the tweak settings and in selected font controller hit “custom fonts” button on you right corner, and should you find your installed font from iFont app.
