### ISSUE TITLE
[Request] Turn off comment ranking

### ISSUE THREAD

**Issue by addisonxx** [BandarHL/BHTwitter#163]
![A5C3EC7E-CCFC-47FC-A301-6DA1C4F2C9B8](https://user-images.githubusercontent.com/99726246/234726265-78c9222a-978d-4755-8257-b8d95d0b49e1.jpeg)
This new feature where blue subscribers’ replies are at the top is super obnoxious. Is there a way to disable this or is it a permanent change?

**Comment by neoighodaro** [comment]
Probably not controllable by software as the rankings would be made on the server before it’s fed to your phone
