### ISSUE TITLE
Will This support on Dopamine jailbreak 

### ISSUE THREAD

**Issue by tom-snow** [BandarHL/BHTwitter#165]

**Comment by BandarHL** [comment]
waiting for [libcephei](https://hbang.github.io/libcephei) to be supported first.

**Comment by tom-snow** [comment]
Cephei for Dopamine seems released, and I try to install the BHTwitter after install Cephei, it shows some dependents errors.

Cephei Tweak Support - sileo://package/ws.hbang.common - from https://repo.chariz.com/

![079F5E42-B50C-4ACB-BF19-4BFA05406A5F](https://github.com/BandarHL/BHTwitter/assets/79245287/d88bba9e-9c00-48d3-9000-6e938bfcb62b)

**Comment by Dr-Sauce** [comment]
It's on BandarHL's Twitter.

https://twitter.com/BandarHL/status/1664725236036534272
