### ISSUE TITLE
(BUG) Crashes on Twitter 9.57

### ISSUE THREAD

**Issue by 4PERTURE** [BandarHL/BHTwitter#167]
The tweak does not seem to work on version 9.57. the app crashes when the tweak is injected.

**Comment by JackPlaysGames0510** [comment]
I’m on 9.58.1 and it works fine

**Comment by 4PERTURE** [comment]
> I’m on 9.58.1 and it works fine

not for me, are you jailbroken?

**Comment by JackPlaysGames0510** [comment]
no

**Comment by 4PERTURE** [comment]
> no

weird, can you send me your ipa or tell me how you injected the deb? maybe it’s a scarlet issue
