### ISSUE TITLE
Latest IPA in Releases tab is very old and buggy

### ISSUE THREAD

**Issue by reticivis-net** [BandarHL/BHTwitter#175]
When viewing an account, the main Tweets tab can’t be scrolled down much
Translations are broken
I think community notes are broken

**Comment by JackPlaysGames0510** [comment]
Use this https://appdb.to/app/cydia/333903828

**Comment by HexCodeFFF** [comment]
Still has the same issues: no translations and can’t scroll in an account’s tweets

**Comment by HexCodeFFF** [comment]
Community notes do work in your version though

**Comment by JackPlaysGames0510** [comment]
toggle off the Always start on the following switch that fixes the first problem I do know about the other ones though

**Comment by HexCodeFFF** [comment]
> toggle off the Always start on the following switch that fixes the first problem I do know about the other ones though

Never have had that setting on
