### ISSUE TITLE
Version 4.0 changes icon and name to X

### ISSUE THREAD

**Issue by SupDos** [BandarHL/BHTwitter#177]
Latest version switches the icon and app name from Twitter to X and changes it in the app as well
Is there any way a release can be made with the last version that had the correct icon and name, or edit them?

**Comment by LPFchan** [comment]
Yeah, option to being able to revert back to Twitter branding would be really nice

**Comment by neoighodaro** [comment]
> …is there any way a release can be made with the last version that had the correct icon and name, or edit them?

Isn’t the correct icon and name X?

**Comment by 96jaco96** [comment]
> > …is there any way a release can be made with the last version that had the correct icon and name, or edit them?
> 
> Isn’t the correct icon and name X?

no it's a bug
