### ISSUE TITLE
Option to open links in safari

### ISSUE THREAD

**Issue by DetachHead** [BandarHL/BHTwitter#18]
The in app browser sucks because it doesn't have extensions

**Comment by BandarHL** [comment]
Sorry but I don’t understand you, can you please provide more details

**Comment by DetachHead** [comment]
Sorry I should've clarified, when you open a link in the app it opens in this in-app browser instead of safari. It would be nice if it would just automatically open in safari instead
![image](https://user-images.githubusercontent.com/57028336/163136562-b71772e7-5961-452b-960c-c5584dd37f1f.jpeg)

**Comment by BandarHL** [comment]
Okay there is an option ‘Always open in Safari’ in BHTwitter settings but just make sure you’re in the lasted update of tweak.
And there some little issues in this option, and yes im working on its will be in the next update beside custom tab bar :)

**Comment by BitGrub** [comment]
I liked this feature, despite the bug that required clicking into something else before to swiping back to get to the home page :L

Please bring it back, Safari has adblocking extensions (and others) that don't work in the in-app browser

**Comment by BandarHL** [comment]
I remove it because it was very buggy (my twitter DM full of reports with this option) and im currently looking for better way to do it with out any buggy stuff in twitter

**Comment by BitGrub** [comment]
I see. Well, I appreciate you looking into it again, thank you.

If I may offer a suggestion, maybe you can add the old method back and attach a warning when you enable it, or a [Beta] label next to it, to hopefully reduce the spam 😅

**Comment by BandarHL** [comment]
If i have not find better way to do it, im going to use your suggestion, thanks.

**Comment by BandarHL** [comment]
it's coming back with the next update :)

**Comment by DavidAGInnovation** [comment]
Hi, with BHTwitter, the Twitter links are opening automatically on Safari. I haven't been able to make the links open in the app automatically. Is there a way to do this?

**Comment by aliafshany** [comment]
@DavidAGInnovation @BandarHL 
yea i confirm that i have faced the same issue.
when i click on a link, it opens safari instead of the app

**Comment by DetachHead** [comment]
disable this in settings if you want the old behavior

![image](https://github.com/user-attachments/assets/c6b99e29-a9c0-4189-b337-662c66701c20)

**Comment by aliafshany** [comment]
> disable this in settings if you want the old behavior
> 
> ![image](https://private-user-images.githubusercontent.com/57028336/398813018-c6b99e29-a9c0-4189-b337-662c66701c20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODQ2NDAsIm5iZiI6MTczNTI4NDM0MCwicGF0aCI6Ii81NzAyODMzNi8zOTg4MTMwMTgtYzZiOTllMjktYTljMC00MTg5LWIzMzctNjYyYzY2NzAxYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA3MjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ODlhNTZkY2I5Mzc0NDU0MWQ2MDI0M2Y4NGQxYjcyMDhmZTU4YTA2Zjk1ZDJjZjg3ZmUzMzgyYThiZGM4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xhurdv89PV9z442IxjggxfXMLSLVfhtBbFU2L7dZ2DQ)

I did disable it, but I still can't open it in X. Also, when I try to open it, there is no sign of X, only the browsers.

**Comment by aliafshany** [comment]
any updates?
