### ISSUE TITLE
Feature Request: ability to remove Twitter spaces thing at the top of TL

### ISSUE THREAD

**Issue by i0ntempest** [BandarHL/BHTwitter#20]
Although this tweak (and the fact that it uses a newer twitter app) is much better, this is one of the features I missed from another tweak. Twitter Fleet (the top bar in timeline tab) is useless and takes up screen real estate.
EDIT: turns out it isn’t fleet anymore but my points still apply

**Comment by BitGrub** [comment]
Twitter Fleets were removed by Twitter themselves about a year ago

**Comment by i0ntempest** [comment]
Well that's... weird. I swear I saw stuff at the top of my timeline yesterday. Could be I loaded a wrong version of IPA.

**Comment by BitGrub** [comment]
Oh that! I think you mean the Twitter Spaces thing that appears when someone you follow begins sermon-ing to whoever will listen. I forgot it was a thing, because my solution was to unfollow anyone still using it

**Comment by i0ntempest** [comment]
Yes, that exactly. Unfollowing isn’t really an option for me cuz I’m following too many ppl lol. Would be even better if you could remove the spaces button at the bottom, or replace it with a tweet button (suggested in another feature request issue).

**Comment by BandarHL** [comment]
Twitter use the same class of Fleets for spaces, so if you install any tweak that remove fleet bar it going to works fine with spaces, and I’ll see if i can add this feature to the next update.
