### ISSUE TITLE
[Feature Request] Option to auto replace x.com with fixvx.com when sharing a link

### ISSUE THREAD

**Issue by WilliamLC98** [BandarHL/BHTwitter#203]
Discord embeds have been broken for a while now, and never properly displayed all the images in a post when sharing normally anyway. As I primarily share tweets to friends and to channels on discord, I’d appreciate if you would consider adding this as a togglable option. The extra time of typing out fixv, stopping it from autocorrecting, then deleting the space every time I share a tweet really adds up.

thank you for your time and for your awesome work on BHTwitter.

**Comment by 8times4** [comment]
btw, this partially / fully fixes this, I just wasn't able to test due to build issues: 
https://github.com/BandarHL/BHTwitter/pull/198
