### ISSUE TITLE
make an altstore repo

### ISSUE THREAD

**Issue by DetachHead** [BandarHL/BHTwitter#21]
@qnblackcat's BHTwitter+ was convenient because there was an [altstore repo](https://qnblackcat.github.io/AltStore/) so i could get updates automatically, but since he stopped updating it [i have to manually check twitter now](https://github.com/qnblackcat/BHTwitter-Plus_Sideloaded/#%EF%B8%8F%EF%B8%8F%EF%B8%8F-please-follow-bandarhelal-bandarhl-on-twitter-to-get-the-latest-version-of-bhtwitter-ipa)

**Comment by BandarHL** [comment]
ok, it seems a good idea

**Comment by DetachHead** [comment]
@BandarHL Is there an AltStore repo now? I can't find it

**Comment by kijijini** [comment]
> @BandarHL Is there an AltStore repo now? I can't find it

Use the ipa for AltStore

**Comment by DetachHead** [comment]
i know you can sideload the ipa in altstore, however a repo would be more convenient since updates can be distributed through altstore instead of having to manually sideload the new versions every time
