### ISSUE TITLE
Infinite loading when downloading with FFmpeg

### ISSUE THREAD

**Issue by korboybeats** [BandarHL/BHTwitter#213]
When trying to download a video with FFmpeg, it will just infinitely load so I have to relaunch the app although the video does actually get downloaded in my photos app.

Video: https://imgur.com/a/g9SNEhB

Device: iPhone 13 Pro Max
iOS: 15.0
Jailbreak: Xina (rootful)
BHTwitter vers: 4.2-1

**Comment by Localls** [comment]
Same thing happens to me. 
But I did notice a workaround for it. 

•click on the video you want to download
•hit the download button
•use FFmpeg (select quality)
•the downloading circle will infinitely spin so…
•swipe off of the video
•after swiping off the loading will stop and it finishes the download! 

Video: https://imgur.com/a/VFjEd5y

Device: iPhone 12 Pro
iOS: 17.0
Jailbreak: none
Sideloaded: AltStore
BHTwitter vers: 4.2-1

**Comment by korboybeats** [comment]
> Same thing happens to me. But I did notice a workaround for it.
> 
> •click on the video you want to download •hit the download button •use FFmpeg (select quality) •the downloading circle will infinitely spin so… •swipe off of the video •after swiping off the loading will stop and it finishes the download!
> 
> Video: https://imgur.com/a/VFjEd5y
> 
> Device: iPhone 12 Pro iOS: 17.0 Jailbreak: none Sideloaded: AltStore BHTwitter vers: 4.2-1

This indeed works 👍 though downloading normally now adds audio again so no need to use FFmpeg for now
