### ISSUE TITLE
is it possible to readd the option to always open app on following tab?

### ISSUE THREAD

**Issue by nyadios** [BandarHL/BHTwitter#214]
hi, i use multiple accounts on twitter and whenever i switch between them it always goes to the 'for you' option, which is pretty annoying to switch back every single time. i saw this option was available on version 3.9 so i tried downloading that one, but due to some twitter errors i cant see quote rts or use the search function (which work just fine on the latest version of this app). thank you!

**Comment by thesoloist-1** [comment]
Yeah this is my only gripe with the app. Not sure why it always opens on the for you page even after I leave X for just a couple minutes. A tweak that will remember your last scroll position would be a great feature. Any possibility for something like this @BandarHL?
