### ISSUE TITLE
“Select url host of tweet after copy” doesn’t work on iPad

### ISSUE THREAD

**Issue by reticivis-net** [BandarHL/BHTwitter#227]
When in landscape, it just freezes and nothing happens

https://github.com/BandarHL/BHTwitter/assets/35177464/1c107d12-2d64-41e5-8db8-ea45f9b823ca

when in portrait, it crashes the app (I clipped the video early to avoid showing my Home Screen which has the weather and my city on it)

https://github.com/BandarHL/BHTwitter/assets/35177464/e22ced69-da4b-4b8d-9510-7301b464cbad

**Comment by BandarHL** [comment]
Sorry for this stupid issue should be fixed in the next update
