### ISSUE TITLE
[feature request]: hide twitter blue users 

### ISSUE THREAD

**Issue by phakoda** [BandarHL/BHTwitter#230]
a feature hiding paid twitter blue users altogether, as most of them are bots. would be greatly appreciated!

**Comment by mattp12** [comment]
Good idea, replies are infested with bots.
But maybe as a "lenient" mode, where it doesn't hide them if you follow them / they follow you.

Or if your followers follow a paid user don't hide those accounts, etc. I imagine it would get taxing if it had to go down many degrees of separation but hopefully what I describe could work.
Not everyone who buys it is a bot, I don't want to blanket hide _all_ of them

**Comment by BoxIsMyNamee** [comment]
+1 to this. this is a fantastic idea. Somebody needs to make this😭

**Comment by BandarHL** [comment]
@phakoda hi, i managed to find a better way to sort and modify the time line without lagging and Ive removed all the twitter blue users.
I really like it the time line and trends is soooo much better without the bots 😂😂.
Also @mattp12 your idea of "lenient" mode is perfect ill make it soon

**Comment by BoxIsMyNamee** [comment]
> @phakoda hi, i managed to find a better way to sort and modify the time line without lagging and Ive removed all the twitter blue users. I really like it the time line and trends is soooo much better without the bots 😂😂. Also @mattp12 your idea of "lenient" mode is perfect ill make it soon

😍😍love to hear it

**Comment by phakoda** [comment]
> @phakoda hi, i managed to find a better way to sort and modify the time line without lagging and Ive removed all the twitter blue users. I really like it the time line and trends is soooo much better without the bots 😂😂. Also @mattp12 your idea of "lenient" mode is perfect ill make it soon

amazing i love to see it. cant wait for the lenient mode!
