### ISSUE TITLE
Custom tab bar not working properly

### ISSUE THREAD

**Issue by waveblitzd** [BandarHL/BHTwitter#233]
Editing the tab bar does nothing on iPhone, it stays the same as before and has this stupid "grok" icon taking up where spaces/communities would go. 
![image](https://github.com/BandarHL/BHTwitter/assets/83782418/4b853ff7-4586-4798-ba5a-5099dde86599)

**Comment by gingerbeardman** [comment]
Did you restart app after making tab bar changes?
