### ISSUE TITLE
Project Abandoned

### ISSUE THREAD

**Issue by CodeWithShreyans** [BandarHL/BHTwitter#246]
Was curious if the project is still being maintained since there hasn't been a commit in 4 months.

**Comment by Chzconey** [comment]
I am wondering the same thing. Will this be updated for Elon's change to X.com?

**Comment by bosconb** [comment]
me too

**Comment by CodeWithShreyans** [comment]
I think it's safe to assume it's abandoned now that it's about to be almost half a year since last commit.

**Comment by CodeWithShreyans** [comment]
Will reopen so people can see.

**Comment by ta6vie** [comment]
I hope it is not...

**Comment by KingGamingYT** [comment]
I tried using this fork, building fails with two makefile errors "/makefiles/common.mk: No such file or directory"

**Comment by Tyri0n** [comment]
> I tried using this fork, building fails with two makefile errors "/makefiles/common.mk: No such file or directory"

I wouldn't bother - I tried it last week and every video I played was followed by a video ad.
I think there were missing context mene options as well.
Deleted it and went back to this BHTwitter.

**Comment by nowesr1** [comment]
> > I tried using this fork, building fails with two makefile errors "/makefiles/common.mk: No such file or directory"
> 
> I wouldn't bother - I tried it last week and every video I played was followed by a video ad. I think there were missing context menu options as well. Deleted it and went back to this BHTwitter.

Hello there. Forgive me for being totally getting used to Github. I did not upload open source for my fork.
You will have to use from releases.
I have provided deb files for all kind of jailbreaks. and sideloaded ipa & TrollStore tipa.
Ads should not be showing

**Comment by Tyri0n** [comment]
> Hello there. Forgive me for being totally getting used to Github. I did not upload open source for my fork. You will have to use from releases. I have provided deb files for all kind of jailbreaks. and sideloaded ipa & TrollStore tipa. Ads should not be showing

I installed a release and video ads played every single time immediately after playing any tweeted video.
Happened about 5 times in a row before I uninstalled it.

**Comment by KingGamingYT** [comment]
> Hello there. Forgive me for being totally getting used to Github. I did not upload open source for my fork.
> 
> You will have to use from releases.
> 
> I have provided deb files for all kind of jailbreaks. and sideloaded ipa & TrollStore tipa.
> 
> Ads should not be showing 

Ah, my bad. I wanted to build with twitter 9.66 since it was one of the last versions still branded as twitter to have support for search.
