### ISSUE TITLE
Pictures Not Loading Correctly 

### ISSUE THREAD

**Issue by qwasedral** [BandarHL/BHTwitter#249]
All pictures on my feed are now showing as “pic.x” links, clicking on the link shows the photo, but it seems like the x app was updated and this is really annoying lol

**Comment by bigfloppa234** [comment]
I am also experiencing this issue on the latest version of BHTwitter

**Comment by Fischake** [comment]
pretty sure this issue is happening with all versions of twitter that are not the latest one as of now. reported to not be working even for users using unmodded but outdated apps.

**Comment by lockieluke** [comment]
it just started happening

**Comment by fosterbarnes** [comment]
I'm gonna try building a version of bhtwitter with the most recent ipa, i'll post a link if it works

**Comment by bigfloppa234** [comment]
Interestingly enough, images now load.

**Comment by Fischake** [comment]
same experience here, ig whatever was changed has been reverted?

**Comment by fosterbarnes** [comment]
welp, glad everything is working now. got linux mint installed just to build this and ran into some errors. in this process i did notice that the "libcephei_URL" link in build.sh is a dead discord attachment link, but linking to libcephei.zip from the latest release on this github page instead should resolve that. Seems like this project is dead as shit lol.

When building I was running into errors as well, could very well be user error, but I installed all dependencies and followed the guides thoroughly. Huge waste of time now that pictures are working, but hey, now I have a linux mint partition.

Here are the errors I receive as well as a text file with what shows when I run `./build.sh`

```
ld: symbol(s) not found for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/foster/theos/makefiles/instance/library.mk:52: /home/foster/BHTwitter/.theos/obj/debug/arm64/BHTwitter.dylib] Error 1
make[2]: *** [/home/foster/theos/makefiles/instance/library.mk:52: /home/foster/BHTwitter/.theos/obj/debug/arm64/BHTwitter.dylib] Error 2
make[1]: *** [/home/foster/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/home/foster/theos/makefiles/master/rules.mk:146: BHTwitter.all.tweak.variables] Error 2
Done, thanks for using BHTwitter.
```

[build.sh.txt](https://github.com/user-attachments/files/16504480/build.sh.txt)

**Comment by Mara-Li** [comment]
Maybe we can make a fork and try to use a github actions for building ?

**Comment by fosterbarnes** [comment]
idk who is building these but someone has "BHX" linked on this github page. not sure if it's the most recent version of x/twitter but it's much newer than anything on this page https://github.com/swaggyP36000/TrollStore-IPAs/releases/tag/08-01-2024
