### ISSUE TITLE
just built & released bhtwitter with a decrypted x ipa (10.59.1) but it gave me a .deb file and im not jailbroken, how do i get it to be an .ipa so i can sideload it to my device?

### ISSUE THREAD

**Issue by comfortablemilk4454** [BandarHL/BHTwitter#259]
just built & released bhtwitter with a decrypted x ipa (10.59.1) but it gave me a .deb file and im not jailbroken, how do i get it to be an .ipa so i can sideload it to my device? thanks so much for any & all help! love this project btw :)

**Comment by comfortablemilk4454** [comment]
to be more specific, i dont understand these directions: https://github.com/BandarHL/BHTwitter#build-for-sideloaded-deployment

**Comment by haxibami** [comment]
These directions are for local builds. If you build with GitHub Actions, you can choose the deployment format when entering URL and other parameters. You may want to choose the `sideloaded` format for `.ipa` files.

![image](https://github.com/user-attachments/assets/bf2bcc27-f238-4d7f-8491-77de4bb27656)

**Comment by comfortablemilk4454** [comment]
tysm that worked!
