### ISSUE TITLE
(bug) Twitter 9.67 crashes when inject with bht twiter 

### ISSUE THREAD

**Issue by bluz69** [BandarHL/BHTwitter#265]
I tried to inject bht twitter deb file in to twitter 9.67 with sideloadly but every time i open it the app crashes. Does anyone have a solution?

**Comment by jakeyounglol** [comment]
strange. i injected it using the github actions thing and it worked

**Comment by bluz69** [comment]
> strange. i injected it using the github actions thing and it worked

do you have the ipa?

**Comment by jakeyounglol** [comment]
yeah here it is https://github.com/jakeyounglol/BHTwitter/releases/tag/v4.3
