### ISSUE TITLE
Force timeline to always be on latest tweets

### ISSUE THREAD

**Issue by ghost** [BandarHL/BHTwitter#27]
Twitter occasionally switches back to “Home” on its own. It would be nice to be able to permanently force “Latest Tweets”.

**Comment by BandarHL** [comment]
That's a good feature, I'm going to look around class to figure it out.

**Comment by BandarHL** [comment]
Its seems Twitter save you option, are sure you're using lasted update of Twitter?![image](https://user-images.githubusercontent.com/31299470/178156968-393dcd25-69f1-4735-968e-80d6b65ef571.png)

**Comment by nyuszika7h** [comment]
Yeah it remembers for a while, but eventually it will switch you back to Home.
