### ISSUE TITLE
User notes feature 

### ISSUE THREAD

**Issue by ghost** [BandarHL/BHTwitter#29]
Something that exists in Discord and I’ve always wanted on Twitter is the ability to attach a short text note to a user. (Ideally it should be tracked by user ID in case the username changes.)

**Comment by BandarHL** [comment]
I don't use discord that much, can you please explain more about it, and where you suggest adding note box? Like in DM info or profile

**Comment by nyuszika7h** [comment]
Not sure what would be the nicest way to do it, but my idea was something like an "info" button on the user profile, maybe a different color if there's already an existing note, and then it shows the note / allows you to edit it.
