### ISSUE TITLE
“Promoted Tweet” heading still appears when hiding ads

### ISSUE THREAD

**Issue by ghost** [BandarHL/BHTwitter#31]
This seems to be an issue with every Twitter ad block tweak. Would it be difficult to also hide the leftover “Promoted Tweet” heading on ads?

**Comment by BandarHL** [comment]
Im sure I'm blocking every ad and their header in the **TIME LINE**, but in there ads in explorer view i can't hide it because they base on swift I can't hook anything on it and in the same time I can't hide the whole class because Twitter use it in another tweets.
