### ISSUE TITLE
Reader feature not working on 2.9.7 and Twitter 9.15.2

### ISSUE THREAD

**Issue by AuroraWright** [BandarHL/BHTwitter#32]
Not sure I'd there's anything I'm missing but i don't see the reader mode icon (which is supposedly next to the "Thread" header) with the above setup (jailed device fwiw).
I recall it was working on a previous version, so it was probably broken
![E6D7C832-E626-4B49-A7D3-AA6B2FEA07BF](https://user-images.githubusercontent.com/15571693/178169044-d10abcea-3ba8-4311-8991-7b2d037b923e.png)

**Comment by BandarHL** [comment]
Yeah it’s seems Twitter change the method where they use to check if User have reader feature or not. Thanks for the report

**Comment by mohmdee** [comment]
BHTwitter.xcodeproj/project.xcworkspace/contents.xcworkspacedata
