### ISSUE TITLE
Remove follower feature

### ISSUE THREAD

**Issue by ghost** [BandarHL/BHTwitter#36]
This already exists on Twitter Web for quite a few months, would be nice to add it to the app as well since I have yet to hear plans from Twitter to add it. Maybe add it to the three dot overflow menu as an option like on web.

Sample request (auth may look a little different in the app):
```
curl 'https://twitter.com/i/api/graphql/QpNfg0kpPRfjROQ_9eOLXA/RemoveFollower' \
  -X POST \
  -H 'authorization: Bearer XXX' \
  -H 'content-type: application/json' \
  -H 'cookie: auth_token=XXX; ct0=XXX' \
  -H 'x-csrf-token: XXX' \
  --data-raw '{"variables":{"target_user_id":"1234567890123456789"},"queryId":"QpNfg0kpPRfjROQ_9eOLXA"}'
```

Note: `QpNfg0kpPRfjROQ_9eOLXA` can be safely hardcoded, it's the persisted GraphQL query ID for `RemoveFollower`.

**Comment by BandarHL** [comment]
I don’t fully understand the feature, do you mean remove all the Following that user have?

**Comment by nyuszika7h** [comment]
No, this feature makes a specific person stop following you. It's similar to blocking and immediately unblocking, except it doesn't force you to also unfollow them (perhaps useful for private accounts).
