### ISSUE TITLE
Themes doesn't apply correctly.

### ISSUE THREAD

**Issue by Isaac7u7** [BandarHL/BHTwitter#40]
Looks like the new update doesn't apply the color of the theme correctly in the header. 

Do you can check it please?
Thank you:)![image](https://user-images.githubusercontent.com/36614732/181415467-b679e7d0-02d1-4b6b-9257-6fc3bd470b11.jpeg)

**Comment by BandarHL** [comment]
Well I think that’s Twitter problem not my Tweak, because BHTwitter run Twitter functions of Thems.
