### ISSUE TITLE
New colors in 2.9.8 do not respect real Twitter Blue color settings

### ISSUE THREAD

**Issue by nyuszika7h** [BandarHL/BHTwitter#43]
I see you added some new colors to buttons in 2.9.8. The problem is that if you have an actual Twitter Blue subscription, BHTwitter doesn't respect the colors set in that, even though when going to the BHTwitter theme selection it correctly shows the one that was selected via the Twitter Blue picker. Also, every time the app is killed and then restarted, it seems to revert back the BHTwitter color to blue, despite the other color still showing as selected.

**Comment by BandarHL** [comment]
Yeah because im keep looking for “bh_color_theme_selectedColor" key

**Comment by BandarHL** [comment]
Fixed with 2.9.9

**Comment by BandarHL** [comment]
> Doesn't seem to be fixed, also Twitter now keeps crashing sometimes on Twitter Blue settings. [Twitter-2022-08-03-164128_ips.txt](https://github.com/BandarHL/BHTwitter/files/9252467/Twitter-2022-08-03-164128_ips.txt)
> 
> **EDIT**: It's just just Twitter Blue settings, it keeps crashing on random actions like liking tweets.

Yeah I noticed some random crashes but until now I don’t know where the problem exactly

**Comment by BandarHL** [comment]
The problem [here](https://github.com/BandarHL/BHTwitter/blob/master/BHTwitter/SettingsViewController.m#L31) with the Observers, I forget to remove it when SettingsViewController is deinitiated

**Comment by nyuszika7h** [comment]
sorry, we conflated two issues here. the crash was fixed but this issue was about the color settings, which are not actually fixed, so please reopen this.

it looks like it's not related to having twitter blue or not at all, but simply the additional colors added by bhtwitter (like the home/latest tweet switch) revert to blue after a force close and restart of the app. the native twitter colors stay the selected color.
