### ISSUE TITLE
Ads on 3.0 don’t work

### ISSUE THREAD

**Issue by JackPlaysGames0510** [BandarHL/BHTwitter#51]
I would put a picture but doesn’t seem to work

**Comment by ike2117** [comment]
Heres a picture happening to me as of today

![image](https://user-images.githubusercontent.com/46185992/188026276-b448cdc2-d1f6-43d2-b6fb-2cab2c778f29.png)

**Comment by seannymurrs** [comment]
Same here

**Comment by D1mar0n** [comment]
iPhone 12 Pro / iOS 14.2 / Unc0ver 8.0.2
Block ADS not working

**Comment by BandarHL** [comment]
Fixed here:
https://github.com/BandarHL/BHTwitter/releases/tag/3.1
