### ISSUE TITLE
Safari Extension isn't showing up in settings | Trollstore 

### ISSUE THREAD

**Issue by RegLoiD** [BandarHL/BHTwitter#53]
Hello! I've installed the iPA via Trollstore ver. 1.0.4. but I can't find the extension in Safari's settings for some reason.

Also, according to Trollstore's developer Opa334, 1.0.4 should support URL schemes. And it actually does, I have uYou+ installed and automatic redirect to YouTube app from Safari link works just fine. Can you please update the iPA so it can work just as Youtube app does?

![image](https://user-images.githubusercontent.com/40953888/188310756-8d064478-85af-4d77-bb34-1f42976ac3e4.png)

**Comment by DetachHead** [comment]
Safari extensions not working [seems to be a trollstore issue](https://twitter.com/opa334dev/status/1566792714724810753). As for the url schemes they should work once the entitlements are fixed. I just raised #54
