### ISSUE TITLE
Ads blocker 

### ISSUE THREAD

**Issue by AlawiYNWA** [BandarHL/BHTwitter#57]
مرحبا بندر 
النسخه الاخيره فيه تعارض مع الاعلانات 
مش محجوبه كامل 
شوف الصوره
شكرا لك
![Uploading 86F6F8B6-F738-49A6-8F84-917825E66B55.png…]()

**Comment by AlawiYNWA** [comment]
![Uploading 70C13BBC-325C-4415-937E-862A5EF77E88.png…]()

**Comment by BandarHL** [comment]
Fixed here:
https://github.com/BandarHL/BHTwitter/releases/tag/3.1
