### ISSUE TITLE
Adblock doesn’t work on 9.26

### ISSUE THREAD

**Issue by JackPlaysGames0510** [BandarHL/BHTwitter#59]
The still not work 
![0619851F-B5F9-4D3C-A1FE-523081CC98FB](https://user-images.githubusercontent.com/48178959/189210711-fbbd6534-368c-4cfc-8a01-58a9e8f06a3e.png)

**Comment by rickymangerie** [comment]
The same issue is happening to me too. Thank you for all your hard work on this tweak!

**Comment by dobby1970** [comment]
I have this issue to

**Comment by BandarHL** [comment]
Fixed here:
https://github.com/BandarHL/BHTwitter/releases/tag/3.1
