### ISSUE TITLE
[Bug] No notifications

### ISSUE THREAD

**Issue by nish4464** [BandarHL/BHTwitter#61]
Hello.

Even though I allow notifications on the ios side, I can't set notifications on the Twitter app side.

I am attaching a screenshot image.

↓

![image](https://user-images.githubusercontent.com/108281977/189510060-68b0b43f-4b71-4b27-9907-9c4905cfe40c.png)![image](https://user-images.githubusercontent.com/108281977/189510061-5341e305-023b-4f68-b384-e1336a7abec9.png)
![image](https://user-images.githubusercontent.com/108281977/189510062-00d92cf2-3d04-43b1-a9fc-967130d1346c.png)

**Comment by seannymurrs** [comment]
Same here.

**Comment by BandarHL** [comment]
It’s not a bug in the tweak, because the notifications fully depends on the certificate and the entitlement that you use to sign the IPA.
