### ISSUE TITLE
Feature request: hide “trending” sidebar on iPad

### ISSUE THREAD

**Issue by HexCodeFFF** [BandarHL/BHTwitter#65]
![E512A1F0-A982-49EA-894C-8B210226363C](https://user-images.githubusercontent.com/35177464/190258137-df095771-28da-4f63-ae81-779f3f99b091.png)

the “trending” view on the right side is always there no matter what, I think a cool feature would be the option to hide it

**Comment by BandarHL** [comment]
You can hide it like that

https://user-images.githubusercontent.com/31299470/190501152-83cb9331-e892-4493-a9d1-c0a5a9d3097b.MOV
