### ISSUE TITLE
Force Logout/App resets after some time

### ISSUE THREAD

**Issue by mobochi** [BandarHL/BHTwitter#67]
Encountered an issue where the app not opened in quite some time in the background forces me to login again and when I do the settings both app and Twitter app resets back to default

using latest bhtwitter
iphone 11 15.0.1 via trollstore
even at prev version had the same issue

**Comment by icpryde** [comment]
Yup I’m also noticing this issue as well!

this is using the latest version with Signulous and on iPhone 14 pro

Twitter9.34_BHTwitter3.2.ipa
