### ISSUE TITLE
[Request] An option to remove the twitter share sheet and replace with the stock iOS share sheet

### ISSUE THREAD

**Issue by PencilNotPen** [BandarHL/BHTwitter#76]
As title, an option in BHTwitter settings to remove the Twitter in-house share sheet and simply invoke the built-in default iOS share sheet, whenever selecting share anywhere within the Twitter app.

Thanks!

**Comment by vwkd** [comment]
“Share via…” should open the system share sheet.

![IMG_0799](https://github.com/user-attachments/assets/d0eb67e6-4fcf-4018-9c7f-3eedd8496874)

**Comment by vwkd** [comment]
“Share via…” should open the system share sheet.

![IMG_0799](https://github.com/user-attachments/assets/133f06e1-dcd7-41c1-9751-6f0135fd8d57)
