### ISSUE TITLE
Suggestion: add a Live Text button to Twitter media

### ISSUE THREAD

**Issue by reticivis-net** [BandarHL/BHTwitter#78]
https://developer.apple.com/documentation/visionkit/enabling_live_text_interactions_with_images

The dev of [Apollo for Reddit](https://apolloapp.io/) claims that the API is “easy and fun to integrate”

![4B880A0E-23CF-41E0-B821-3E228F554AB3](https://user-images.githubusercontent.com/35177464/204051735-da7d67fb-416c-4df1-87d9-7394436649a3.jpeg)

![006DAD9F-A443-4C4C-A86C-54BD5374F7A9](https://user-images.githubusercontent.com/35177464/204051677-df96ccc4-0079-462e-ac1e-4bfda00fd2a5.jpeg)
![D3E9041B-2761-4C6C-BF35-4C6034FE9998](https://user-images.githubusercontent.com/35177464/204051681-764f2b8a-ee57-46e0-9fa3-b54ab0571410.jpeg)
![1EDB7489-6203-46C6-9277-B830D9A3FB9A](https://user-images.githubusercontent.com/35177464/204051680-2830bf33-81b1-48d7-b252-04e794f2189f.jpeg)

**Comment by BandarHL** [comment]
Great suggestion, I'm going to work on it.

**Comment by Void48** [comment]
> Great suggestion, I'm going to work on it.

any update on this?
