### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Duckyz95** [BandarHL/BHTwitter#8]
It would be great to be able to put the tweet button back to the bottom bar instead of the large floating button we have now.

**Comment by Brodomtk** [comment]
https://github.com/BandarHL/BHTwitter/blob/ca8e19e228c29a6b7396ed6fabd64d2d44f343f2/BHTwitter/BHDownload.h

**Comment by Brodomtk** [comment]
https://github.com/BandarHL/BHTwitter/blob/ca8e19e228c29a6b7396ed6fabd64d2d44f343f2/BHTwitter/BHDownload.h
