### ISSUE TITLE
Suggestion/Request: hide/change icon for Twitter Blue “verified” people

### ISSUE THREAD

**Issue by HexCodeFFF** [BandarHL/BHTwitter#80]
The API treats the new Twitter Blue “verification” differently from true verification, as is evident by Blue not showing checkmarks in older app versions and when going to their profile and tapping the checkmark it tells you if it’s from Blue or not. I think there should be an option to either completely hide Blue checkmarks or change the icon to something else.

sorry for the blank issue originally I accidentally hit enter

**Comment by BandarHL** [comment]
I'm currently thinking about changing the color of the verification mark.

**Comment by BandarHL** [comment]
> I'm currently thinking about changing the color of the verification mark.

Well Twitter dit it with last version

**Comment by HexCodeFFF** [comment]
Actually the new colors don’t cover *all* “legacy” verified accounts. Yellow is for business and grey is for government but famous individuals, for example, still have a blue mark so I think an option to distinguish or just hide Blue “verification” would still be useful
