### ISSUE TITLE
[Bug] Copy user info link with Chinese username failure

### ISSUE THREAD

**Issue by CySxL** [BandarHL/BHTwitter#81]
Crash log : https://pastebin.com/eY88rZ1S

Device : iPhone 11 Pro Max
iOS : 14.8
Jailbreak tool : unc0ver 8.0.2
Twitter : 9.34.6
Substitute : 2.2.3
BHTwitter : 3.3

When trying to copy the link of a user's main/home page, twitter crashes immediately.  

Found that the culprit might be the users using Chinese letters as their  full name.

Demonstration : https://streamable.com/pkej2p

**Comment by BandarHL** [comment]
according to the crash log, BHTwitter is trying to copy a 'nil' value, which should be fixed next update.
