### ISSUE TITLE
Can't install on Sileo

### ISSUE THREAD

**Issue by DetachHead** [BandarHL/BHTwitter#83]
How do I install Bhtwitter using Sileo? It seems to be on the havoc repo, but when I tap "add source" and search for it there, it's no longer present
![image](https://user-images.githubusercontent.com/57028336/206207408-1db5c141-53dd-423a-a662-d1b43c0cba7f.png)
![image](https://user-images.githubusercontent.com/57028336/206207477-5836590c-0c5e-4481-af70-7118e75e68cd.png)
![image](https://user-images.githubusercontent.com/57028336/206207508-8d20090a-03bf-454b-87e0-574d40290894.png)

**Comment by BandarHL** [comment]
install it from Release page

**Comment by DetachHead** [comment]
@BandarHL It would be more convenient if I could install it from Sileo so I don't have to manually check GitHub for updates
