### ISSUE TITLE
[Request] Re-Add “Twitter for [Device]” label

### ISSUE THREAD

**Issue by arichorn** [BandarHL/BHTwitter#88]
Newest twitter update eliminates the text “twitter for iPhone” and everywhere else
The reason why this change is bad is because you cannot tell if the the user who tweeted is real or isn’t a bot. Based on the label. Screw Elon.
![E80CC38C-943A-4C72-B02E-012A98A3BC96](https://user-images.githubusercontent.com/78001398/208204082-55e85961-270b-4a1b-87bc-97fae813ca9c.jpeg)

**Comment by arichorn** [comment]
Also this is a very important thing to have on Twitter
Reasons
**1. Checking if it’s a Real Person**
This reason is very obvious when you use twitter like here’s an example if you ever had a problem with your channel going to TeamYouTube and saying there’s an issue you may not know if it’s automated so you go to their tweet and check if they’re the real deal. It would show “Sprinklr” which would indicate that it’s a botted tweet as of not being real. Elon making it invisible will now make it an issue with a ton of users having situations like this.
**2. Being Trustful**
If you tried posting your tweets using tweet bots from any site, people would know that you were using a bot to post random tweets but since anyone can’t even see it now your random tweets will no longer show any label using any bot which results with your followers having trust issues against you.

these reasons were very bad when explaining to them. Sorry about this BanderHL I was trying to be descriptive of why it deserves a return and thanks for letting us hide the view count now. Very appreciate that one.

**Comment by BandarHL** [comment]
I’m working on it. Just last night I found where twitter save this info. Should be in next version

**Comment by arichorn** [comment]
Thanks BandarHL! You’re awesome 👍😅
