### ISSUE TITLE
Suggestion: beautify the numbers under a tweet

### ISSUE THREAD

**Issue by HexCodeFFF** [BandarHL/BHTwitter#92]
So normally when you click on a tweet you see the stats labeled with text
![6BE9866C-8374-4F83-B6AF-084DF3529CC5](https://user-images.githubusercontent.com/35177464/209405693-a00dfb66-bb03-4d52-a23c-baa1d802adfe.jpeg)
My suggestion would be (an option to) merge the stats view with the icons like it is when you’re looking at a tweet in your feed
![CE6E7A81-3F49-49A9-9DA3-2A0734B78312](https://user-images.githubusercontent.com/35177464/209405823-0e0c415c-ecaa-4ba8-af3f-9afd0063ae64.jpeg)
There’d need to be a different icon for quote tweets
I think tapping on the icon would initiate the action (like/retweet) and tapping on the number would look at the users who did the action

maybe this is a bad suggestion but idk

**Comment by BandarHL** [comment]
I don't think there is enough space to show the number and the download button.

**Comment by HexCodeFFF** [comment]
Ah fair enough. Just an idea cause the current layout is ugly lmao
