### ISSUE TITLE
[Bug] Share as image fails.

### ISSUE THREAD

**Issue by CySxL** [BandarHL/BHTwitter#93]
Twitter: 9.38
BHTwitter: 3.5

Sometimes when entering a tweet from home feeds, the share as image stops working in them.

Video demo:
https://streamable.com/eww2fu

Screenshot:
![image](https://user-images.githubusercontent.com/15531137/209760364-0a951076-6a50-422c-ba8e-9700a1e75240.png)

**Comment by BandarHL** [comment]
Are sure you in the lasted version of BHTwitter? (Because it’s work for me)

**Comment by CySxL** [comment]
> Are sure you in the lasted version of BHTwitter? (Because it’s work for me)

Yeah man. 100% sure. I even tried downgraded and upgraded to 3.8 again.

**Comment by CySxL** [comment]
> Are sure you in the lasted version of BHTwitter? (Because it’s work for me)

Sorry for the misinformation !! I checked again and the installation of 3.5 failed in past due to other packages' dpkg error, now reinstall it again and all fine ❤️❤️❤️
