### ISSUE TITLE
BHTwitter always asking to identify myself.

### ISSUE THREAD

**Issue by craftgeil** [BandarHL/BHTwitter#98]
So Twitter asks me like twice a day to identify its me by asking my password.

On my iPad I also use BHTwitter but it never asked me there to identify. Any idea why this is?

![3EA61721-95CD-43BA-9278-FCC18428A3F1](https://user-images.githubusercontent.com/80261988/211159052-5e85059f-799d-40dd-bc18-84e91fe8200e.jpeg)

**Comment by BandarHL** [comment]
Make sure you're using the lasted version on the released page.
